"""Shared data-loading helpers for all app pages.

One source of truth for file paths and loading/validation logic, so no page
duplicates another page's parsing or error handling. Every function reads
already-computed, committed aggregate outputs from data/processed/ or
outputs/ -- the app never touches restricted KDHS microdata and never
recomputes an analysis that scripts/*.R already owns.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import pandas as pd
import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT = PROJECT_ROOT.parent  # the qmd source files (Project7_task2*.qmd) live here, not under project7-maternal-child-health/
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"
OUTPUTS = PROJECT_ROOT / "outputs"

REGIONAL_SUMMARY = DATA_PROCESSED / "task2_stunting_summary.json"
IMMUNISATION_SUMMARY = DATA_PROCESSED / "task2_immunisation_summary.json"
SBA_SUMMARY = DATA_PROCESSED / "task2_sba_summary.json"
COUNTY_STUNTING = DATA_PROCESSED / "task2_stunting_by_county.csv"
COUNTY_IMMUNISATION = DATA_PROCESSED / "task2_immunisation_by_county.csv"
COUNTY_SBA = DATA_PROCESSED / "task2_sba_by_county.csv"
WEALTH_QUINTILE = DATA_PROCESSED / "task2_wealth_quintile.csv"
WEALTH_CONCENTRATION = DATA_PROCESSED / "task2_wealth_concentration_indices.json"
PRIORITY_COUNTIES = DATA_PROCESSED / "task4_priority_counties.csv"
WEALTH_NOTE = DATA_PROCESSED / "task4_wealth_note.txt"
HAZ_HISTOGRAM = OUTPUTS / "figures" / "task2_haz_histogram.png"
COUNTY_MAP = OUTPUTS / "maps" / "county_stunting_map.png"
IMMUNISATION_MAP = OUTPUTS / "maps" / "county_immunisation_map.png"
SBA_MAP = OUTPUTS / "maps" / "county_sba_map.png"

# Recovered from origin/task2-regional-indicators (Plots/, figures/), pulled 2026-08-04.
# Real, rendered images -- not regenerated by this branch's own pipeline.
PLOTS_DIR = REPO_ROOT / "Plots"
FIGURES_DIR = REPO_ROOT / "figures"

STUNTING_FOREST_PLOT = PLOTS_DIR / "Stunting_forest_plot.png"
VACCINATION_FOREST_PLOT = PLOTS_DIR / "Vaccination_forest_plot.png"
SBA_FOREST_PLOT = PLOTS_DIR / "Sba_forest_plot.png"
COMBINED_CC_GRAPHS = PLOTS_DIR / "combined_cc_graphs.png"
COMBINED_MAPS = PLOTS_DIR / "combined_maps.png"
COMBINED_CLUSTER_OBSERVED_PREV = PLOTS_DIR / "combined_cluster_observed_prev_graphs.png"
COMBINED_VARIOGRAMS = PLOTS_DIR / "combined_variograms_plots.png"
COMBINED_CORRELATION = PLOTS_DIR / "combined_correlation_plots.png"
COMBINED_PREDICTED = PLOTS_DIR / "combined_predicted_graphs.png"
FIG_HAZ_VIOLIN = FIGURES_DIR / "fig-haz-violin-1.png"
FIG_TOP_COUNTIES_RANKING = FIGURES_DIR / "fig-top-counties-ranking-1.png"
FIG_WEALTH_CATEGORY_INDICATORS = FIGURES_DIR / "fig-wealth-category-indicators-1.png"

# Current headline national stunting prevalence, 12-35 month band -- see
# task2_stunting_summary.json for provenance. Used everywhere the app states
# "the" national stunting figure, for cross-tab consistency.
NATIONAL_STUNTING_PCT = 21.7
# The county-level v1 intervention ranking (task4_priority_counties.csv) was
# computed on the earlier 6-59 month county CSV and hasn't been re-run on the
# 12-35 month band -- its own internal threshold math must stay tied to the
# band it was actually computed on, not the current headline figure above.
# See PLAN.md § Recovered analysis for the age-band discrepancy this reflects.
NATIONAL_STUNTING_PCT_6_59_LEGACY = 17.4

SDG_LINKS = {
    "stunting": {
        "code": "SDG 2.2.1",
        "goal": "End all forms of malnutrition by 2030",
        "why": "Stunting is the vital metric for long-term chronic undernutrition, which irreversibly impairs physical and cognitive development.",
    },
    "immunisation": {
        "code": "SDG 3.b.1",
        "goal": "Provide affordable essential medicines and vaccines, and advance universal health coverage",
        "why": "Full immunisation safeguards infant health by establishing community-level immunity against preventable infectious diseases.",
    },
    "sba": {
        "code": "SDG 3.1.2",
        "goal": "Reduce the global maternal mortality ratio to less than 70 per 100,000 live births",
        "why": "Skilled birth attendance prevents intrapartum complications from becoming fatal.",
    },
}


def _fail(message: str) -> None:
    """Show a clear, actionable error instead of an uncaught traceback, then halt the page."""
    st.error(message, icon="🚫")
    st.stop()


@st.cache_data(show_spinner=False)
def get_regional_summary() -> dict:
    try:
        with open(REGIONAL_SUMMARY, encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        _fail(
            f"Missing `{REGIONAL_SUMMARY.relative_to(PROJECT_ROOT)}`. "
            "Run `make regional` (`scripts/regional_analysis.R`) against real KDHS data to generate it."
        )
    except json.JSONDecodeError as e:
        _fail(f"`{REGIONAL_SUMMARY.relative_to(PROJECT_ROOT)}` is not valid JSON: {e}")


@st.cache_data(show_spinner=False)
def get_immunisation_summary() -> dict:
    try:
        with open(IMMUNISATION_SUMMARY, encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        _fail(f"Missing `{IMMUNISATION_SUMMARY.relative_to(PROJECT_ROOT)}`.")
    except json.JSONDecodeError as e:
        _fail(f"`{IMMUNISATION_SUMMARY.relative_to(PROJECT_ROOT)}` is not valid JSON: {e}")


@st.cache_data(show_spinner=False)
def get_sba_summary() -> dict:
    try:
        with open(SBA_SUMMARY, encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        _fail(f"Missing `{SBA_SUMMARY.relative_to(PROJECT_ROOT)}`.")
    except json.JSONDecodeError as e:
        _fail(f"`{SBA_SUMMARY.relative_to(PROJECT_ROOT)}` is not valid JSON: {e}")


@st.cache_data(show_spinner=False)
def get_county_stunting() -> pd.DataFrame:
    try:
        df = pd.read_csv(COUNTY_STUNTING)
    except FileNotFoundError:
        _fail(
            f"Missing `{COUNTY_STUNTING.relative_to(PROJECT_ROOT)}`. "
            "Run `make regional` (`scripts/regional_analysis.R`) against real KDHS data to generate it."
        )
    expected = {"county", "prevalence_pct", "ci_lower", "ci_upper"}
    missing = expected.difference(df.columns)
    if missing:
        _fail(
            f"`{COUNTY_STUNTING.relative_to(PROJECT_ROOT)}` is missing expected "
            f"column(s): {', '.join(sorted(missing))}."
        )
    return df.sort_values("prevalence_pct", ascending=False)


def _read_county_csv(path: Path) -> pd.DataFrame:
    try:
        df = pd.read_csv(path)
    except FileNotFoundError:
        _fail(f"Missing `{path.relative_to(PROJECT_ROOT)}`.")
    expected = {"county", "prevalence_pct", "ci_lower", "ci_upper"}
    missing = expected.difference(df.columns)
    if missing:
        _fail(f"`{path.relative_to(PROJECT_ROOT)}` is missing expected column(s): {', '.join(sorted(missing))}.")
    return df.sort_values("prevalence_pct", ascending=False)


@st.cache_data(show_spinner=False)
def get_county_immunisation() -> pd.DataFrame:
    return _read_county_csv(COUNTY_IMMUNISATION)


@st.cache_data(show_spinner=False)
def get_county_sba() -> pd.DataFrame:
    return _read_county_csv(COUNTY_SBA)


def has_wealth_quintile_data() -> bool:
    return WEALTH_QUINTILE.exists()


@st.cache_data(show_spinner=False)
def get_wealth_quintile() -> pd.DataFrame | None:
    if not has_wealth_quintile_data():
        return None
    return pd.read_csv(WEALTH_QUINTILE)


def has_wealth_concentration_data() -> bool:
    return WEALTH_CONCENTRATION.exists()


@st.cache_data(show_spinner=False)
def get_wealth_concentration() -> dict | None:
    if not has_wealth_concentration_data():
        return None
    with open(WEALTH_CONCENTRATION, encoding="utf-8") as f:
        return json.load(f)


@st.cache_data(show_spinner=False)
def get_priority_counties() -> pd.DataFrame:
    try:
        df = pd.read_csv(PRIORITY_COUNTIES)
    except FileNotFoundError:
        _fail(
            f"Missing `{PRIORITY_COUNTIES.relative_to(PROJECT_ROOT)}`. "
            "Run `make intervention` (`scripts/intervention_prioritization.R`) to generate it."
        )
    return df.sort_values("priority_rank")


def get_wealth_note() -> str:
    if WEALTH_NOTE.exists():
        return WEALTH_NOTE.read_text(encoding="utf-8").strip()
    return (
        "Wealth-quintile data not yet available — county geography is "
        "currently the only prioritization axis. See the Wealth Analysis page."
    )


@st.cache_data(show_spinner=False)
def get_file_bytes(path: Path) -> bytes | None:
    """Cached raw bytes for a committed file, for st.download_button. None if missing."""
    p = Path(path)
    if not p.exists():
        return None
    return p.read_bytes()


@dataclass(frozen=True)
class DataFile:
    label: str
    path: Path
    task: str
    status: str  # "available" | "preliminary" | "missing"
    note: str


def data_inventory() -> list[DataFile]:
    """Live status of every file in docs/data_dictionary.md -- re-checked on every call.

    Single source of truth for the Data page's completeness table and the
    Downloads page's file list, so the two can never drift out of sync.
    """
    return [
        DataFile(
            "National stunting summary", REGIONAL_SUMMARY, "Task 2",
            "available" if REGIONAL_SUMMARY.exists() else "missing",
            "12–35 month band, survey-weighted, 21.7% (see provenance in the file).",
        ),
        DataFile(
            "National immunisation summary", IMMUNISATION_SUMMARY, "Task 2",
            "available" if IMMUNISATION_SUMMARY.exists() else "missing",
            "12–35 month band, survey-weighted, 50.3%.",
        ),
        DataFile(
            "National SBA summary", SBA_SUMMARY, "Task 2",
            "available" if SBA_SUMMARY.exists() else "missing",
            "12–35 month band, survey-weighted, 88.8%.",
        ),
        DataFile(
            "County stunting (47 counties, 95% CI)", COUNTY_STUNTING, "Task 2",
            "preliminary" if COUNTY_STUNTING.exists() else "missing",
            "6–59 month band -- kept for the v1 intervention ranking's internal consistency; superseded nationally by the 12–35mo figure above.",
        ),
        DataFile(
            "HAZ histogram", HAZ_HISTOGRAM, "Task 2",
            "available" if HAZ_HISTOGRAM.exists() else "missing",
            "National distribution of height-for-age z-scores.",
        ),
        DataFile(
            "Wealth-equity concentration indices", WEALTH_CONCENTRATION, "Task 2",
            "preliminary" if WEALTH_CONCENTRATION.exists() else "missing",
            "Stunting/immunisation/SBA — recovered from a rendered PDF on another branch, not yet reproduced in this branch's pipeline.",
        ),
        DataFile(
            "County stunting forest plot / map (12–35mo)", STUNTING_FOREST_PLOT, "Task 2",
            "preliminary" if STUNTING_FOREST_PLOT.exists() else "missing",
            "Recovered, current band; national reference line = 21.7%.",
        ),
        DataFile(
            "County immunisation forest plot / map (12–35mo)", VACCINATION_FOREST_PLOT, "Task 2",
            "preliminary" if VACCINATION_FOREST_PLOT.exists() else "missing",
            "Recovered; national reference line = 50.3%.",
        ),
        DataFile(
            "County SBA forest plot / map (12–35mo)", SBA_FOREST_PLOT, "Task 2",
            "preliminary" if SBA_FOREST_PLOT.exists() else "missing",
            "Recovered; national reference line = 88.8%.",
        ),
        DataFile(
            "Wealth-category (Low/Middle/High) indicator comparison", FIG_WEALTH_CATEGORY_INDICATORS, "Task 2",
            "preliminary" if FIG_WEALTH_CATEGORY_INDICATORS.exists() else "missing",
            "3-category wealth breakdown for all three indicators, recovered image.",
        ),
        DataFile(
            "County immunisation (47 counties, 12–35mo)", COUNTY_IMMUNISATION, "Task 2",
            "preliminary" if COUNTY_IMMUNISATION.exists() else "missing",
            "Extracted from the forest-plot image pixels, not a rendered R output — see docs/data_dictionary.md.",
        ),
        DataFile(
            "County SBA (47 counties, 12–35mo)", COUNTY_SBA, "Task 2",
            "preliminary" if COUNTY_SBA.exists() else "missing",
            "Extracted from the forest-plot image pixels, not a rendered R output — see docs/data_dictionary.md.",
        ),
        DataFile(
            "Priority counties (Task 4 v1, stunting only)", PRIORITY_COUNTIES, "Task 4",
            "available" if PRIORITY_COUNTIES.exists() else "missing",
            "Ranked, from the 6–59mo stunting county data.",
        ),
        DataFile(
            "Multi-indicator vulnerability ranking (Task 4 v2)", FIG_TOP_COUNTIES_RANKING, "Task 4",
            "preliminary" if FIG_TOP_COUNTIES_RANKING.exists() else "missing",
            "Recovered image; top-10 counties by # indicators in worst tertile across all three outcomes.",
        ),
        DataFile(
            "Wealth-equity note (Task 4)", WEALTH_NOTE, "Task 4",
            "available" if WEALTH_NOTE.exists() else "missing",
            "Auto-generated placeholder until the quintile CSV lands.",
        ),
    ]


def page_footer(extra: str | None = None) -> None:
    """Consistent provenance/vintage caption at the bottom of every page."""
    st.divider()
    text = "KDHS 2022 · Eneza Data Science Residential Training 2026 · Project 7"
    if extra:
        text += f" · {extra}"
    st.caption(text)
