"""Spatial & Bayesian Analysis: a status/audit page, not a results page.

Deliberately does not fabricate any INLA/MBG output. Shows what exists (the
recovered static maps, real but preliminary), what's prepared but unrun
(the INLA/MBG source), and exactly what's missing to run it -- per the
audit in docs/task2_audit_report.md.
"""

import sys
from pathlib import Path

import pandas as pd
import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from utils import IMMUNISATION_MAP, REPO_ROOT, SBA_MAP, COUNTY_MAP, page_footer

st.set_page_config(page_title="Spatial & Bayesian Analysis — Project 7", page_icon="🌐", layout="wide")

st.title("🌐 Spatial & Bayesian Analysis")
st.caption("What's spatial in this project today, and what INLA/MBG would add once runnable")

st.subheader("What exists today: recovered static choropleths")
st.markdown(
    "These are real, committed images — not placeholders — but they are "
    "**recovered from a teammate's branch**, not produced by a fitted "
    "spatial model. They're simple survey-weighted county aggregates joined "
    "to `rKenyaCensus` boundaries, the same numbers shown on the Regional "
    "Analysis page."
)
maps = st.columns(3)
for col, (label, path) in zip(
    maps,
    [("Stunting", COUNTY_MAP), ("Immunisation", IMMUNISATION_MAP), ("Skilled birth attendance", SBA_MAP)],
):
    with col:
        st.markdown(f"**{label}**")
        if path.exists():
            st.image(str(path), use_container_width=True)
        else:
            st.info("Not available.", icon="⏳")
st.caption(
    "12–35 month age band, recovered 2026-08-02 from `origin/task2-regional-indicators`. "
    "See `PLAN.md` § Recovered analysis for full provenance."
)

st.divider()
st.subheader("What INLA / MBG would add")
st.markdown(
    "A county choropleth answers *\"what's the average in county X\"*. A "
    "fitted spatial model (INLA or MBG) instead estimates a **continuous "
    "surface** — prevalence at any point in Kenya, smoothed using "
    "information from nearby survey clusters — with **explicit, "
    "pixel-level uncertainty** (standard deviation, 95% credible interval "
    "width) rather than one confidence interval per county. This is "
    "materially more informative for sub-county targeting, which is why "
    "it's flagged as a stretch goal rather than a core Task 2 deliverable."
)

st.divider()
st.subheader("Code inventory")
st.caption("Every spatial/Bayesian source file in this repo, and exactly where each one stops.")

rows = []
for indicator in ["stunting", "immunisation", "sba"]:
    inla_path = REPO_ROOT / f"Project7_task2_inla_{indicator}.qmd"
    mbg_path = REPO_ROOT / f"Project7_task2_2_mbg_{indicator}.qmd"
    for method, path, stops_at in [
        ("INLA", inla_path, "Rendered map of predicted prevalence (`maps` chunk) — furthest along of any spatial file here"),
        ("MBG", mbg_path, "Variogram diagnostic of residual spatial correlation — prep for a kriging fit that hasn't been written yet"),
    ]:
        if path.exists():
            n_lines = len(path.read_text(encoding="utf-8").splitlines())
            rows.append({"Indicator": indicator.replace("sba", "Skilled birth attendance").title(), "Method": method, "File": path.name, "Lines": n_lines, "Status": "Prepared, not executed", "Stops at": stops_at})
        else:
            rows.append({"Indicator": indicator.title(), "Method": method, "File": path.name, "Lines": "—", "Status": "Missing", "Stops at": "—"})

st.dataframe(pd.DataFrame(rows), hide_index=True, use_container_width=True)

st.divider()
st.subheader("Exactly what's missing to execute any of this")
st.error(
    "1. **Raw KDHS 2022 microdata** (`KEKR8BFL.DTA`) — restricted-access, "
    "approved DHS Program data request required. Not committed to this "
    "repo, per `PLAN.md` § Repository rules.\n\n"
    "2. **DHS geographic cluster shapefile** (`KEGE8AFL.shp`) — a *separate* "
    "restricted-access DHS Program geographic-data request. Required for "
    "cluster GPS coordinates; without it there is no spatial location to "
    "model against.\n\n"
    "3. **R 4.3+** with `INLA` (non-CRAN — "
    "`install.packages(\"INLA\", repos=\"https://inla.r-inla-download.org/R/stable\")`), "
    "`PrevMap`, `sf`, `terra`, `tmap`, `survey`, `gtsummary`. None installed "
    "in the environment this app was audited in (no R interpreter at all).\n\n"
    "4. For the adjusted-OR chunks specifically: three CSVs under "
    "`Data/Derived_estimates/` (`dhs_stunting_WI_adjusted_OR.csv`, "
    "`..._immunisation_...`, `..._sba_...`) — referenced by "
    "`Project7_task2.qmd` but not generated by any script in this repo yet.",
    icon="🚫",
)
st.markdown(
    "None of the above is invented here — see `docs/task2_audit_report.md` "
    "for the full gap analysis and exactly which requirement each blocker "
    "maps to."
)

page_footer("Spatial & Bayesian Analysis")
