"""Spatial & Bayesian Analysis: observed prevalence, model diagnostics, and
predicted-probability surfaces for stunting, immunisation, and SBA.

Two complementary small-area-estimation approaches were run: MBG
(model-based geostatistics) and INLA (Bayesian SPDE). Images here are real,
rendered outputs recovered from origin/task2-regional-indicators -- not
regenerated by this app, which has no R/INLA environment of its own.
"""

import sys
from pathlib import Path

import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from utils import (
    COMBINED_CLUSTER_OBSERVED_PREV,
    COMBINED_CORRELATION,
    COMBINED_PREDICTED,
    COMBINED_VARIOGRAMS,
    page_footer,
)

st.set_page_config(page_title="Spatial & Bayesian Analysis — Project 7", page_icon="🌐", layout="wide")

st.title("🌐 Spatial & Bayesian Analysis")
st.caption("Model-based geostatistics (MBG) and Bayesian spatial (INLA) small-area estimation, all three indicators")

st.subheader("Model specification")
st.markdown("**Likelihood:**")
st.latex(r"y_i \mid p_i \sim \text{Binomial}(n_i, p_i), \quad i = 1, \dots, N")
st.markdown("**Linear predictor:**")
st.latex(r"\text{logit}(p_i) = \beta_0 + \mathbf{X}_i^\top \boldsymbol{\beta} + Z(s_i) + \epsilon_i")
st.markdown(
    "Where $y_i$, $n_i$ are the number of cases and individuals sampled at "
    "cluster $i$; $\\mathbf{X}_i^\\top \\boldsymbol{\\beta}$ are the fixed "
    "effects (covariates); $Z(s_i)$ is the spatial random effect; and "
    "$\\epsilon_i$ is unstructured random noise (nugget). Source: "
    "`Presentation.Rmd` § MBG Model Specification."
)

st.divider()
st.subheader("Sampled locations and observed prevalence")
if COMBINED_CLUSTER_OBSERVED_PREV.exists():
    st.image(
        str(COMBINED_CLUSTER_OBSERVED_PREV),
        caption="DHS cluster locations and observed prevalence, stunting / immunisation / SBA.",
        width="stretch",
    )
else:
    st.info("Not available.", icon="⏳")

st.divider()
st.subheader("Preliminary checks")
tab_corr, tab_vario = st.tabs(["Multicollinearity", "Variograms"])
with tab_corr:
    if COMBINED_CORRELATION.exists():
        st.image(str(COMBINED_CORRELATION), caption="Correlation between candidate covariates.", width="stretch")
    else:
        st.info("Not available.", icon="⏳")
with tab_vario:
    if COMBINED_VARIOGRAMS.exists():
        st.image(str(COMBINED_VARIOGRAMS), caption="Empirical variograms — residual spatial correlation by indicator.", width="stretch")
    else:
        st.info("Not available.", icon="⏳")

st.divider()
st.subheader("Predicted probabilities")
if COMBINED_PREDICTED.exists():
    st.image(
        str(COMBINED_PREDICTED),
        caption="Model-predicted prevalence surfaces, stunting / immunisation / SBA.",
        width="stretch",
    )
    st.markdown(
        "The predicted surface smooths prevalence across space using "
        "information from nearby clusters, rather than reporting one flat "
        "estimate per county — visible here as continuous color gradients "
        "that cut across county lines. County boundaries are overlaid for "
        "geographic reference only, not as prediction breaks."
    )
else:
    st.info("Not available.", icon="⏳")

st.caption(
    "Source: `Project7_task2_inla_*.qmd`, `Project7_task2_2_mbg_*.qmd` "
    "(INLA/MBG pipelines), `MCH_Kenya_Task2_Task4_Pipeline.qmd` (Phase 12/12B). "
    "Full methodology: the Methodology page."
)

page_footer("Spatial & Bayesian Analysis")
